name: Survival
version: live
main: me.theminecoder.mcsurvival.Survival
website: https://github.com/theminecoder/mcsurvival
commands:
  tpa:
    description: Request to teleport to another online player with this command!
    usage: /tpa <target>
  tpaccept:
    description: Accept pending teleport requests
    usage: /tpaccept
  tpdeny:
    description: Deny pending teleport requests
    usage: /tpdeny
  msg:
    description: Message a player
    usage: /msg <target> <message>
    aliases: [m, message, t, tell, w, whisper]
  r:
    description: Reply to a message
    usage: /r <message>
    aliases: [reply]
  reloaddata:
    description: Reload main data files
    usage: /reloaddata